### ISSUE TITLE
Organization Access

### ISSUE THREAD

**Issue by sathishsoundharajan** [dwyl/learn-codeclimate#6]
Hi,

When i hit signup with github. i got below screen.
![organization_access](https://cloud.githubusercontent.com/assets/8023447/10557655/73b12f82-74d2-11e5-9f05-9f5f40a08734.PNG)

Does this mean codeclimate can access dwyl informations?
If so, how can i restrict it?
Is it bad?

**Comment by nelsonic** [comment]
Good question @bboysathish 
Don't worry, **_ALL**_ our data is **100% Open Source** so feel free to Authorize CodeClimate. :+1:

**Comment by sathishsoundharajan** [comment]
@nelsonic  Open Source!! I Love it!!!!!!
